### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by eyildiz-ugoe** [SUYEgit/Surgery-Robot-Detection-Segmentation#11]
If you have 11 classes, you get the following error in your `real_time_detection.py`.

```
Traceback (most recent call last):
  File "detection.py", line 49, in <module>
    class_names, p['scores'], colors=colors, real_time=True)
  File "/usr/local/lib/python3.5/dist-packages/mask_rcnn-2.1-py3.5.egg/mrcnn/visualize.py", line 136, in display_instances
IndexError: list index out of range
```

It works with 2 and 5 classes, but not with 11.

Any thoughts?

**Comment by monjurulkarim** [comment]
Give mask color using 'Label' name instead of class_id.

**Comment by eyildiz-ugoe** [comment]
Sorry could you elaborate that a bit? Which class and which function should I look into? @rajubuet24

**Comment by monjurulkarim** [comment]
Did it work?

**Comment by eyildiz-ugoe** [comment]
The issue was about something else, everything is solved now.
