### ISSUE TITLE
VIA dataset

### ISSUE THREAD

**Issue by david-schweitzer** [SUYEgit/Surgery-Robot-Detection-Segmentation#4]
Hello, could you provide a snippet of your VIA annotations?  I have a script that creates annotations on the fly based on what's in the data/surgery/... folders, and it's mostly matched up with what VIA does individually, but a few lines I'm not certain about.

For example, in surgery.py on line 165, you have

#"name" is the attributes name decided when labeling, etc. 'region_attributes': {name:'a'}
class_names = info["names"]

But from the comment, there is no "names" key in "region_attributes."  And these are not necessarily universal or required labeling means in VIA since VIA has apparently a few ways of identifying what regions are.

**Comment by SUYEgit** [comment]
Thanks for your comment. Yeah you are correct. I really appreciate your reviewing. That line of code is forgotten to be moved to before line 172.
 'names' are defined in function ```add_image```. 'name' is the attribute name which is self-defined when labeling. I will update it soon! Thank you!

**Comment by david-schweitzer** [comment]
This issue can be closed since everything can be found here (for others):  #3
