### ISSUE TITLE
AttributeError: 'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by eyildiz-ugoe** [SUYEgit/Surgery-Robot-Detection-Segmentation#9]
As described in the balloon example, I've used VIA tool to annotate my images. I've used circles, polygons, etc. and gave each class its respective name.

![1](https://user-images.githubusercontent.com/35396058/45495438-8c6ee500-b773-11e8-9aa1-803026bf4db0.png)
![2](https://user-images.githubusercontent.com/35396058/45495439-8c6ee500-b773-11e8-9d1c-146e1bea9724.png)

Now that I want to load the dataset,  using your code, and I get the following error:

```
Traceback (most recent call last):
  File "components.py", line 522, in <module>
    train(model)
  File "components.py", line 231, in train
    dataset_train.load_components(args.dataset, "train")
  File "components.py", line 124, in load_components
    polygons = [r['shape_attributes'] for r in a['regions'].values()]
AttributeError: 'list' object has no attribute 'values'

```

What could be the problem? Has anyone tried loading the annotated data which contains circles? (not only polygons)

P.S: Here is the code snippet (taken from `surgery.py`) to load the data.

 ```
# Add images
        for a in annotations:
            # Get the x, y coordinaets of points of the polygons that make up
            # the outline of each object instance. There are stored in the
            # shape_attributes (see json format above)
            polygons = [r['shape_attributes'] for r in a['regions'].values()]
            names = [r['region_attributes'] for r in a['regions'].values()]
            # load_mask() needs the image size to convert polygons to masks.
            # Unfortunately, VIA doesn't include it in JSON, so we must read
            # the image. This is only managable since the dataset is tiny.
            image_path = os.path.join(dataset_dir, a['filename'])
            image = skimage.io.imread(image_path)
            height, width = image.shape[:2]

            self.add_image(
                "components",
                image_id=a['filename'],  # use file name as a unique image id
                path=image_path,
                width=width, height=height,
                polygons=polygons,
                names=names)
```

**Comment by eyildiz-ugoe** [comment]
It's because the loader only accepts polygons, which is quite bad, tbh.

**Comment by Gauravi24** [comment]
> It's because the loader only accepts polygons, which is quite bad, tbh.

i have polylines would it still not work.
What is the other way to load any idea

**Comment by eyildiz-ugoe** [comment]
No, it has to be polygons. And it has been long time so I kinda lost my touch to that project, sorry, can't help further I am afraid.

**Comment by Gauravi24** [comment]
Thank you.
